### ISSUE TITLE
Προσθήκη του mydrupal.gr στον πλανήτη

### ISSUE THREAD

**Issue by KostasBlank** [greek-libre-planet/greek-libre-planet#20]
Θα σας παρακαλούσα να προστεθεί στον πλανήτη ΕΛΛ/ΛΑΚ το ακόλουθο feed, από τη σελίδα της ελληνικής κοινότητας drupal,http://mydrupal.gr

http://mydrupal.gr/taxonomy/term/5/feed

Ευχαριστώ εκ των προτέρων 
kostask

**Comment by comzeradd** [comment]
Απ' ότι βλέπω υπάρχει ήδη, αλλά έχει το [full feed](http://mydrupal.gr/rss.xml). Θες απλά να αλλάξει το feed;

**Comment by KostasBlank** [comment]
Δεν το είχα δει, έψαχνα στο m για mydrupal και όχι στο d ...

Άστο έτσι όπως είναι.
