### ISSUE TITLE
Προσθήκη Avatar

### ISSUE THREAD

**Issue by ndrosis** [greek-libre-planet/greek-libre-planet#21]
Καλησπέρα,

πως μπορώ να προσθέσω avatar?

**Comment by comzeradd** [comment]
Καλησπέρα,

Μπορείς να παραθέσεις ένα url για το avatar σου (ή απλά να το σύρεις σε ένα comment) και μετά μπορώ να το περάσω.

Το avatar κατά προτίμηση να είναι μόνο το κεφάλι. Δες [εδώ](http://planet.hellug.gr/images/avatars/) τα avatars που υπάρχουν ήδη για να πάρεις μια ιδέα.

**Comment by ndrosis** [comment]
![dolibarr_124x124_gr](https://cloud.githubusercontent.com/assets/4933899/7344885/806e3530-ecd8-11e4-890d-768978ad36f9.png)
Είναι για το dolibarr.gr
Σε ευχαριστώ πολύ.
