### ISSUE TITLE
Προσθήκη Diginsite Blog στο Πλανήτης ΕΛ/ΛΑΚ

### ISSUE THREAD

**Issue by AimiliaGp** [greek-libre-planet/greek-libre-planet#34]
Καλησπέρα,
θα ήθελα να προσθέσω το Blog με όνομα: Diginsite Blog
και url: https://diginsiteblog.wordpress.com/

Η θεματολογία αφορά νέα σχετικά με το Ίντερνετ και το Δίκαιο του Ίντερνετ (Πνευματική ιδιοκτήσία, Προστασία προσωπικών δεδομένων, Δίκαιο Τηλεπικοινωνιών κ.α.) στην ελληνική και αγγλική γλώσσα!

Ευχαριστώ,
Αιμιλία

**Comment by axilleas** [comment]
Καλησπέρα, θα βάλω για tag το `planet`, οπότε το μόνο που έχεις να κάνεις είναι να το δημιουργήσεις στο wordpress και την επόμενη φορά που θα κάνεις νέο post και θέλεις να βγει στο planet βάλτου το `planet` tag.
