### ISSUE TITLE
Προσθήκη blog palavitsinis.wordpress.com

### ISSUE THREAD

**Issue by palavitsinis** [greek-libre-planet/greek-libre-planet#36]
Θα ήθελα να προσθέσω το blog μου στη λίστα. 

Είναι το https://palavitsinis.wordpress.com/ όπου δημοσιεύω άρθρα σχετικά με ανοικτούς εκπαιδευτικούς πόρους αλλά και με μεταδεδομένα, κυρίως σχετικά με την εκπαίδευση αλλά και πιο ευρείες θεματικές. 

Υπάρχει κάποιο tag με το οποίο μπορώ να επισημαίνω μόνο τα άρθρα εκείνα που θέλω να "τραβηχτούν" από το planet?

Ευχαριστώ

**Comment by axilleas** [comment]
Καλησπέρα, θα χρησιμοποιήσω το gfoss tag (https://palavitsinis.wordpress.com/tag/gfoss/feed/) οπότε από δω και στο εξής ό,τι θες να βγαίνει στο planet και έχει σχέση με το open, βάλτου αυτό το tag.

**Comment by Polichronucci** [comment]
Καλησπέρα, τι όνομα θα ήθελες να φαίνεται στο Planet για το feed σου?

**Comment by palavitsinis** [comment]
Από ότι βλέπω χρησιμοποιείτε τα ονόματα στα ελληνικά αν δε κάνω λάθος, οπότε Νίκος Παλαβιτσίνης είναι ΟΚ...
