### ISSUE TITLE
Μεταφραστική ομάδα KDE

### ISSUE THREAD

**Issue by pvidalis** [greek-libre-planet/greek-libre-planet#44]
Καλησπέρα, 
επικοινωνώ εκ μέρους της μεταφραστικής ομάδας του KDE.
Επαναφέραμε τη λειτουργία της σελίδας μας, σε νέο domain οπότε αντίστοιχα άλλαξε και η διεύθυνση RSS που είχαμε.

Όνομα: Μεταφραστική ομάδα KDE
Feed: http://www.kde.gr/rss.xml
avatar: http://www.kde.gr/sites/all/themes/kde/logo.png

Ευχαριστώ

**Comment by Polichronucci** [comment]
Added.
