### ISSUE TITLE
Add iridakos.com

### ISSUE THREAD

**Issue by iridakos** [greek-libre-planet/greek-libre-planet#48]
Καλησπέρα,

>...μπορείς να ζητήσεις την προσθήκη του blog σου δηλώνοντας το feed της κατηγορίας, του tag, ή το γενικό feed του blog σου, το όνομα/επώνυμο σου και προαιρετικά το avatar σου...

## Ιστολόγιο
Θα ήθελα να προσθέσω το ιστολόγιό μου [iridakos.com](https://iridakos.com).
Τα άρθρα είναι κυρίως τεχνικά και αφορούν προγραμματιστές αλλά σχετίζονται με το ανοιχτό λογισμικό.

## Feed urls
Σας παραθέτω δύο feed ώστε να αποφασίσετε ποιο ταιριάζει περισσότερο σε περίπτωση προσθήκης.
- Για όλα τα άρθρα: https://iridakos.com/feed.xml
- Για άρθρα που αφορούν μόνο το ανοιχτό λογισμικό: https://iridakos.com/feeds/opensource.xml

## Ονοματεπώνυμο
Λάζαρος Λαζαρίδης

## Avatar
Μπορείτε να χρησιμοποιήσετε την [εικόνα του προφίλ μου στο GitHub](https://avatars0.githubusercontent.com/u/9477868?s=460&v=4).

Ευχαριστώ πολύ

**Comment by iridakos** [comment]
Καλημέρα,

Μπορείτε να αλλάξετε το feed URL που χρησιμοποιείτε για το blog μου στο παρακάτω URL ώστε να εμφανίζονται μόνο τα άρθρα που αφορούν στο ελεύθερο λογισμικό;

https://iridakos.com/feeds/opensource.xml

Ευχαριστώ πολύ.

**Comment by axilleas** [comment]
https://github.com/greek-libre-planet/greek-libre-planet/commit/1b95d06bb88ab23e990185c9821b3783953ed9de
