### ISSUE TITLE
Προσθήκη των ελληνικών άρθρων - https://iridakos.com/el/

### ISSUE THREAD

**Issue by iridakos** [greek-libre-planet/greek-libre-planet#55]
Γεια χαρά,

Άρχισα να γράφω και άρθρα στα [ελληνικά](https://iridakos.com/el/).

Το feed για τα ελληνικά άρθρα που σχετίζονται με τον προγραμματισμό και το ανοιχτό λογισμικό είναι το παρακάτω.

https://iridakos.com/el/feeds/programming.xml

Ευχαριστώ πολύ!

**Comment by ellakdev** [comment]
Καλησπέρα,

Στο commit https://github.com/greek-libre-planet/greek-libre-planet/commit/393d12420ebc6d826c2a9b623f7c83d88de00d24 προστέθηκε και το δεύτερο feed του blog σας. Ενημερώστε αν συμφωνείτε με τα ονόματα ή αν θέλετε κάποια αλλαγή, ώστε να κλείσω το issue.

Ευχαριστώ

**Comment by iridakos** [comment]
Μια χαρά είναι τα ονόματα, ευχαριστώ πολύ!
