### ISSUE TITLE
Προσθήκη blog στον πλανήτη

### ISSUE THREAD

**Issue by tellidis** [greek-libre-planet/greek-libre-planet#56]
Γεια χαρά,
Προσθέστε παρακαλώ το blog μου στον Πλανήτη. 

Όνομα:  Ιωακείμ Τελλίδης

Feed:    https://noosphere.gr/index.php/archives/tag/planet

Ευχαριστώ.

**Comment by tellidis** [comment]
Κάποιο update παιδιά;

**Comment by ellakdev** [comment]
Καλησπέρα,

Το feed του blog σας προστέθηκε.

Ευχαριστώ
