### ISSUE TITLE
Τροποποίηση RSS feed

### ISSUE THREAD

**Issue by tellidis** [greek-libre-planet/greek-libre-planet#57]
Καλημέρα,

Θα μπορούσατε να **ενημερώσετε** το feed του blog μου στο παρακάτω;

Όνομα: Ιωακείμ Τελλίδης

https://noosphere.gr/tags/planet/feed.xml

Ευχαριστώ.

**Comment by ellakdev** [comment]
Ανανεώθηκε το feed με το καινούριο
