### ISSUE TITLE
Ενημέρωση RSS feed

### ISSUE THREAD

**Issue by tellidis** [greek-libre-planet/greek-libre-planet#58]
Συγνώμη που απασχολώ ξανά, αλλά θα μπορούσε κάποιος να ενημερώσει το feed του blog μου?

**Ιωακείμ Τελλίδης**

Feed:   https://noosphere.gr/index.php/archives/tag/planet/feed
Tag:     https://noosphere.gr/index.php/archives/tag/planet/

Ευχαριστώ.

**Comment by ellakdev** [comment]
Ανανεώθηκε το feed με το καινούριο 31a4140465c99c56a7b0f8d65d0b631fb79e3c44
