### ISSUE TITLE
Προσθήκη linuxuser.gr

### ISSUE THREAD

**Issue by jtsagata** [greek-libre-planet/greek-libre-planet#59]
Αν και είμαστε φόρουμ υπάρχει πολύ χρήσιμο υλικό και άρθρα. Φτιάξαμε λοιπόν το 

https://linux-user.gr/tag/planet.rss

για να βάζουμε όποιον αξιόλογο οδηγό ή άρθρο μπει. Για να αποφευχθεί το spamming μόνον οι διαχειριστές έχουν το δικαίωμα να μαρκάρουν μια δημοσίευση.  Παρακαλώ προσθέστε το.

Ευχαριστώ

**Comment by jtsagata** [comment]
Έχουμε κάτι νεώτερο ;

**Comment by ellakdev** [comment]
Προστέθηκε το feed 3b61393452302bfaa8fd385e7b278387f85c5be6

**Comment by jtsagata** [comment]
Δεν δείχνει το feed. Μπορείτε να δείτε τι συμβαίνει και τι μπορεί να γίνει;
