### ISSUE TITLE
Προσθήκη του feed του συνεδρίου FOSSCOMM 2024

### ISSUE THREAD

**Issue by iosifidis** [greek-libre-planet/greek-libre-planet#66]
Παρακαλούμε όπως εισάγετε το feed του συνεδρίου FOSSCOMM 2024.

To feed είναι το παρακάτω:
Ιστοσελίδα: [https://2024.fosscomm.gr/](https://2024.fosscomm.gr/)   
Feed: [https://2024.fosscomm.gr/feed/](https://2024.fosscomm.gr/feed/)   
Logo: [Logo](https://pbs.twimg.com/profile_images/1829076828088049664/Zl5ZT92L_400x400.png)

![FOSSCOMM2024](https://github.com/user-attachments/assets/51afab35-af90-46cc-a998-50d5774f50b5)

**Comment by ellakdev** [comment]
Το feed του συνεδρίου FOSSCOMM 2024 προστέθηκε.

**Comment by iosifidis** [comment]
Δεν φαίνεται το εικονίδιο (σε εμένα δηλαδή)

![planet-ellak-fosscomm24](https://github.com/user-attachments/assets/a0af626f-b634-4646-8cbd-dd31e70f90d2)

Είναι κάτι δικό μας ή από την πλευρά του planet;

**Comment by ellakdev** [comment]
Διορθώθηκε.
